Bug fixes & new/expanded test cases
molinch/ConfigurationSubstitutor pull request #13
Opened 2021-12-31 01:53 UTC by a-alamoudi

- [FIX] Applied fixes to `EnableSubstitutionsWithDelimitedFallbackDefaults` to match behaviour of `EnableSubstitutions` when handling non-resolvable variables and `null` substituted values.
- [TEST] Added and expanded a couple of test cases to ensure the latest fixes.

2021-12-31 08:03 UTC, molinch requested changes

2021-12-31 08:03 UTC, molinch commented on ConfigurationSubstitutor/ConfigurationSubstitutor.cs
> +                        // if declared EV isn't resolvable, assign it to provided fallback default value
Could you elaborate on what means EV?

2021-12-31 08:03 UTC, molinch commented on ConfigurationSubstitutor/ConfigurationSubstitutor.cs
> +                            configuration[delimitedVals[0]] = delimitedVals[1];
I know this was already added in former PR, but I somehow missed that.
Not a big fan of altering source configuration, if we can keep the function pure and pass the value downwards sounds simpler/better to reason about. What do you think?

2021-12-31 08:43 UTC, a-alamoudi commented on ConfigurationSubstitutor/ConfigurationSubstitutor.cs
> +                        // if declared EV isn't resolvable, assign it to provided fallback default value
Absolutely, 'EV' refers to an environment variable. This section deals with the two tokens produced from breaking the captured value by the specified delimiter. Once execution arrives at this code segment, we're sure the delimiter matches, and that the first part (i.e., `delimitedVals[0]`) is the environment variable (EV).
Let's take the following example:
```
"Foo" = "${Var1:default_val}"
```
Substituting `config["Foo"]` with the start mark specified as `${`, the end mark as `}` and delimiter as `:`; we'd end up with `Var1` as the EV.

2021-12-31 17:25 UTC, a-alamoudi commented
https://github.com/molinch/ConfigurationSubstitutor/pull/13#discussion_r776949125 @molinch I took another crack at it and avoided altering the source configuration by using a local dictionary instead. It passes all of the existing tests and behaves just the same. Please review and let me know what you think.
Thanks, and Happy New Year! 🙂

2022-01-01 08:26 UTC, molinch commented on ConfigurationSubstitutor/ConfigurationSubstitutor.cs
> +                        // if declared EV isn't resolvable, assign it to provided fallback default value
Thanks for the explanation

2022-01-02 16:42 UTC, molinch approved these changes
Only did minor changes, thanks a lot @a-alamoudi !

2022-01-02 16:42 UTC, merged

2022-01-02 16:44 UTC, molinch commented
On nuget as 1.4.1, have a very nice 2022 year!

2022-01-02 17:19 UTC, a-alamoudi commented
@molinch Awesome! Thanks a lot, you too 😊